# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170421_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='lg_photo/%Y/%m/%d/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_sm',
            field=models.ImageField(blank=True, upload_to='small_photo/%Y/%m/%d/', verbose_name='предпросмотр'),
        ),
    ]
