# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170421_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_photo', models.ImageField(blank=True, upload_to='musician', verbose_name='Фотография участника группы')),
                ('name', models.CharField(max_length=200, verbose_name='Имя(в любом формате')),
                ('desc', models.TextField(verbose_name='Подробная информация/ описание/ биография и т.д.')),
                ('links', models.CharField(blank=True, max_length=500, verbose_name='Ссылки на другие проекты/ профили')),
            ],
        ),
    ]
