# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_header', models.CharField(blank=True, max_length=300, verbose_name='Заголовок главного текста(например название группы)')),
                ('main_text', models.TextField(blank=True, verbose_name='Главный текс (о группе)')),
                ('display', models.BinaryField(blank=True)),
            ],
        ),
    ]
