# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_maintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintext',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
