# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170425_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BG_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name=' название изображения')),
                ('bg', models.ImageField(blank=True, upload_to='backgrouns/%Y/%m/%d/', verbose_name='Фоновое Изображение 1920х1080 px ')),
                ('display', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
        ),
    ]
