# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bg_image',
            name='name',
        ),
    ]
