# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170502_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (200символов)')),
                ('header2', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (200символов)')),
                ('header3', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (200символов)')),
                ('header4', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (200символов)')),
                ('header5', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (200символов)')),
                ('image', models.ImageField(blank=True, upload_to='afisha/%Y/%m/%d/', verbose_name='Афиша  150х200px')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo_alboom',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
