# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170508_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='body',
            field=models.CharField(blank=True, max_length=500, verbose_name='код видео(заходим на YuoTube, выбираем "поделиться" и копируем все что после "https://youtu.be/" сюда!'),
        ),
    ]
