# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 15:40
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170508_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('alboom', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
        ),
    ]
